name: weathergpt_mobile
description: WeatherGPT Mobile for Android and iOS.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  speech_to_text: ^7.4.0
  flutter_tts: ^4.0.2
  record: ^6.2.1
  dio: ^5.4.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  easy_localization: ^3.0.7
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
